//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdealParameter
    {
        public long id { get; set; }
        public string age { get; set; }
        public long gender { get; set; }
        public string excursion { get; set; }
        public string dinamometry { get; set; }
    }
}
