//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserParameter
    {
        public long idUser { get; set; }
        public double weight { get; set; }
        public double height { get; set; }
        public double excursion { get; set; }
        public double dynamometry { get; set; }
        public string dateOfStart { get; set; }
        public string dateOfEnd { get; set; }
        public long IdTraining { get; set; }
        public long level { get; set; }
    
        public virtual Training Training { get; set; }
        public virtual User User { get; set; }
    }
}
